### ISSUE TITLE
Use of `.server()` method in Cypress 12 is causing tests to fail

### ISSUE THREAD

**Issue by jkantner** [RcKeller/cypress-unfetch#12]
I attempted an upgrade to Cypress 12.1.0 for an app I’ve been working on, and I got this error when I tried to run any test:

```
  1) "before each" hook for "An uncaught error was detected outside of a test"

  0 passing (3s)
  1 failing

  1) "before each" hook for "An uncaught error was detected outside of a test":
     CypressError: `cy.server()` was removed in Cypress version 12.0.0. Please update to use `cy.intercept()` instead.

https://on.cypress.io/intercept

Because this error occurred during a `before each` hook we are skipping all of the remaining tests.
      at Context.server (http://localhost:4200/__cypress/runner/cypress_runner.js:146611:83)
      at wrapped (http://localhost:4200/__cypress/runner/cypress_runner.js:156304:43)
  From Your Spec Code:
      at Context.eval (webpack:///./node_modules/@rckeller/cypress-unfetch/await.js:24:0)
```

It turns out the code involving `cy.server()` needs to be reworked to use `cy.intercept()` as the error says.

**Comment by jkantner** [comment]
@RcKeller Any input on this?

**Comment by mkonir0** [comment]
@RcKeller Any plans for handling this? 🙏

**Comment by jkantner** [comment]
It turns out this project is abandoned. The last commit was over 4 years ago. Closing my issue.
